# Generated by Django 3.2.13 on 2022-06-04 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import kikeou.models.abstracts.cycle_dependents


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "accommodation",
                "verbose_name_plural": "accommodations",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
            },
        ),
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_the_active_one",
                    models.BooleanField(
                        default=False, verbose_name="is the active one"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
            ],
            options={
                "verbose_name": "cycle",
                "verbose_name_plural": "cycles",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="street & n°"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="zip code"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=50, verbose_name="city"),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        default=kikeou.models.abstracts.cycle_dependents.CycleDependentManager.get_default_cycle,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="location_related",
                        to="kikeou.cycle",
                        verbose_name="cycle",
                    ),
                ),
            ],
            options={
                "verbose_name": "location",
                "verbose_name_plural": "locations",
            },
        ),
        migrations.CreateModel(
            name="Lodge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gauge",
                    models.PositiveSmallIntegerField(default=0, verbose_name="gauge"),
                ),
                (
                    "ground_floor",
                    models.BooleanField(default=False, verbose_name="ground floor"),
                ),
                (
                    "soundproofed",
                    models.BooleanField(default=False, verbose_name="soundproofed"),
                ),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lodge",
                        to="kikeou.location",
                        verbose_name="location",
                    ),
                ),
            ],
            options={
                "verbose_name": "lodge",
                "verbose_name_plural": "lodges",
            },
        ),
        migrations.CreateModel(
            name="WarmUpPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warmupplace",
                        to="kikeou.location",
                        verbose_name="location",
                    ),
                ),
            ],
            options={
                "verbose_name": "warm-up place",
                "verbose_name_plural": "warm-up places",
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_lodge",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_stage_assignations",
                        to="kikeou.lodge",
                        verbose_name="default lodge",
                    ),
                ),
                (
                    "default_warming_up_place",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_stage_assignations",
                        to="kikeou.warmupplace",
                        verbose_name="default warm up place",
                    ),
                ),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage",
                        to="kikeou.location",
                        verbose_name="location",
                    ),
                ),
            ],
            options={
                "verbose_name": "stage",
                "verbose_name_plural": "stages",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="last name"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="phone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "diet_type",
                    models.CharField(
                        choices=[
                            ("omnivore", "omnivore"),
                            ("vegetarian", "vegetarian"),
                            ("vegan", "vegan"),
                        ],
                        default="omnivore",
                        max_length=10,
                        verbose_name="diet type",
                    ),
                ),
                (
                    "diet_allergies",
                    models.TextField(
                        blank=True, verbose_name="allergies / intolerances"
                    ),
                ),
                (
                    "is_greeter",
                    models.BooleanField(default=False, verbose_name="is greeter"),
                ),
                (
                    "is_location_contact",
                    models.BooleanField(
                        default=False, verbose_name="is location contact"
                    ),
                ),
                (
                    "is_programmer",
                    models.BooleanField(default=False, verbose_name="is programmer"),
                ),
                (
                    "is_stage_manager",
                    models.BooleanField(default=False, verbose_name="is stage manager"),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        default=kikeou.models.abstracts.cycle_dependents.CycleDependentManager.get_default_cycle,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="person_related",
                        to="kikeou.cycle",
                        verbose_name="cycle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "person",
                "verbose_name_plural": "persons",
            },
        ),
        migrations.AddConstraint(
            model_name="cycle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_the_active_one", True)),
                fields=("is_the_active_one",),
                name="unique_is_the_active_one",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="cycle",
            field=models.ForeignKey(
                default=kikeou.models.abstracts.cycle_dependents.CycleDependentManager.get_default_cycle,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="company_related",
                to="kikeou.cycle",
                verbose_name="cycle",
            ),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="location",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accommodation",
                to="kikeou.location",
                verbose_name="location",
            ),
        ),
        migrations.CreateModel(
            name="Greeter",
            fields=[],
            options={
                "verbose_name": "greeter person",
                "verbose_name_plural": "greeter persons",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("kikeou.person",),
        ),
        migrations.CreateModel(
            name="LocationContact",
            fields=[],
            options={
                "verbose_name": "location contact",
                "verbose_name_plural": "location contacts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("kikeou.person",),
        ),
        migrations.CreateModel(
            name="Programmer",
            fields=[],
            options={
                "verbose_name": "programmer person",
                "verbose_name_plural": "programmer persons",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("kikeou.person",),
        ),
        migrations.CreateModel(
            name="StageManager",
            fields=[],
            options={
                "verbose_name": "stage manager",
                "verbose_name_plural": "stage managers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("kikeou.person",),
        ),
        migrations.AddField(
            model_name="location",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locations",
                to="kikeou.locationcontact",
                verbose_name="lodge contact",
            ),
        ),
    ]
