# Generated by Django 3.2.13 on 2022-05-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kikeou", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cycle",
            name="is_the_active_one",
            field=models.BooleanField(default=False, verbose_name="is the active one"),
        ),
        migrations.AddConstraint(
            model_name="cycle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_the_active_one", True)),
                fields=("is_the_active_one",),
                name="unique_is_the_active_one",
            ),
        ),
    ]
