# Generated by Django 3.2.13 on 2022-06-05 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kikeou", "0002_person_age_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Greeter",
        ),
        migrations.DeleteModel(
            name="LocationContact",
        ),
        migrations.DeleteModel(
            name="Programmer",
        ),
        migrations.DeleteModel(
            name="StageManager",
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_greeter",
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_location_contact",
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_programmer",
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_stage_manager",
        ),
        migrations.CreateModel(
            name="StageManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stagemanager",
                        to="kikeou.person",
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "stage manager",
                "verbose_name_plural": "stage managers",
            },
        ),
        migrations.CreateModel(
            name="Programmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programmer",
                        to="kikeou.person",
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "programmer person",
                "verbose_name_plural": "programmer persons",
            },
        ),
        migrations.CreateModel(
            name="LocationContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locationcontact",
                        to="kikeou.person",
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "location contact",
                "verbose_name_plural": "location contacts",
            },
        ),
        migrations.AlterField(
            model_name="Location",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locations",
                to="kikeou.locationcontact",
                verbose_name="lodge contact",
            ),
        ),
        migrations.CreateModel(
            name="Greeter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="greeter",
                        to="kikeou.person",
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "greeter person",
                "verbose_name_plural": "greeter persons",
            },
        ),
    ]
