# Generated by Django 3.2.13 on 2022-06-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kikeou", "0002_alter_location_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="showstaffmember",
            options={
                "verbose_name": "staff member",
                "verbose_name_plural": "staff members",
            },
        ),
    ]
