# Generated by Django 3.2.13 on 2022-06-05 12:13

import django.db.models.deletion
from django.db import migrations, models

import kikeou.models.abstracts.cycle_dependents


class Migration(migrations.Migration):

    dependencies = [
        ("kikeou", "0003_auto_20220605_0851"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="name")),
                (
                    "cycle",
                    models.ForeignKey(
                        default=kikeou.models.abstracts.cycle_dependents.CycleDependentManager.get_default_cycle,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="showtype_related",
                        to="kikeou.cycle",
                        verbose_name="cycle",
                    ),
                ),
            ],
            options={
                "verbose_name": "show type",
                "verbose_name_plural": "show types",
            },
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=15, verbose_name="code"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "size",
                    models.CharField(blank=True, max_length=20, verbose_name="size"),
                ),
                (
                    "accessories",
                    models.TextField(blank=True, verbose_name="accessories"),
                ),
                ("storage", models.TextField(blank=True, verbose_name="storage")),
                (
                    "show_duration",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="show duration (minutes)"
                    ),
                ),
                (
                    "setup_duration",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="setup duration (minutes)"
                    ),
                ),
                (
                    "roadmap_remarks",
                    models.TextField(blank=True, verbose_name="roadmap remarks"),
                ),
                (
                    "info_sheet_remarks",
                    models.TextField(
                        blank=True, verbose_name="information sheet remarks"
                    ),
                ),
                (
                    "greeter_remarks",
                    models.TextField(blank=True, verbose_name="greeter remarks"),
                ),
                (
                    "food_remarks",
                    models.TextField(blank=True, verbose_name="food remarks"),
                ),
                (
                    "default_staff_arrival",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="staff arrival time (default)",
                    ),
                ),
                (
                    "arrival_remarks",
                    models.TextField(blank=True, verbose_name="arrival remarks"),
                ),
                (
                    "last_minute_arrival",
                    models.BooleanField(
                        default=False, verbose_name="last minute arrival"
                    ),
                ),
                (
                    "default_staff_departure",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="staff departure (default)"
                    ),
                ),
                (
                    "mean_of_travel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("motorized", "motorized vehicle"),
                            ("walker", "walker"),
                        ],
                        default="",
                        max_length=9,
                        verbose_name="mean of travel",
                    ),
                ),
                ("vehicles", models.TextField(blank=True, verbose_name="vehicles")),
                (
                    "accommodation_remarks",
                    models.TextField(blank=True, verbose_name="accommodation remarks"),
                ),
                (
                    "programmer_remarks",
                    models.TextField(blank=True, verbose_name="programmer remarks"),
                ),
                (
                    "stage_manager_remarks",
                    models.TextField(blank=True, verbose_name="stage manager remarks"),
                ),
                (
                    "need_lodge",
                    models.BooleanField(
                        default=None, null=True, verbose_name="need lodge"
                    ),
                ),
                (
                    "lodge_people",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="people in lodge"
                    ),
                ),
                (
                    "lodge_duration_before",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="time in lodge before the show (minutes)",
                    ),
                ),
                (
                    "lodge_duration_after",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="time in lodge after the show (minutes)",
                    ),
                ),
                (
                    "need_lodge_catering",
                    models.BooleanField(
                        default=None, null=True, verbose_name="catering in lodge"
                    ),
                ),
                (
                    "lodge_remarks",
                    models.TextField(blank=True, verbose_name="lodge remarks"),
                ),
                (
                    "need_warm_up",
                    models.BooleanField(
                        default=None, null=True, verbose_name="need warm up"
                    ),
                ),
                (
                    "warm_up_duration",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="warm up duration (minutes)"
                    ),
                ),
                (
                    "warm_up_spaces_remarks",
                    models.TextField(blank=True, verbose_name="warm up spaces remarks"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shows",
                        to="kikeou.company",
                        verbose_name="company",
                    ),
                ),
                (
                    "default_accommodation",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shows",
                        to="kikeou.accommodation",
                        verbose_name="accommodation (default)",
                    ),
                ),
                (
                    "default_lodge",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shows",
                        to="kikeou.lodge",
                        verbose_name="lodge (default)",
                    ),
                ),
                (
                    "default_warm_up_place",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warm_up_shows",
                        to="kikeou.warmupplace",
                        verbose_name="warm up place (default)",
                    ),
                ),
                (
                    "greeter",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shows",
                        to="kikeou.greeter",
                        verbose_name="greeter",
                    ),
                ),
                (
                    "programmer",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shows",
                        to="kikeou.programmer",
                        verbose_name="programmer",
                    ),
                ),
                (
                    "stage_manager",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shows_as_stage_manager",
                        to="kikeou.stagemanager",
                        verbose_name="stage manager",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kikeou.showtype",
                        verbose_name="show type",
                    ),
                ),
            ],
            options={
                "verbose_name": "show",
                "verbose_name_plural": "shows",
            },
        ),
    ]
