# Generated by Django 3.2.13 on 2022-06-03 23:19

import django.db.models.deletion
from django.db import migrations, models

import kikeou.models.utils.abstracts


class Migration(migrations.Migration):

    dependencies = [
        ("kikeou", "0003_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="cycle",
            field=models.ForeignKey(
                default=kikeou.models.utils.abstracts.get_default_cycle,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="person_related",
                to="kikeou.cycle",
                verbose_name="cycle",
            ),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "cycle",
                    models.ForeignKey(
                        default=kikeou.models.utils.abstracts.get_default_cycle,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company_related",
                        to="kikeou.cycle",
                        verbose_name="cycle",
                    ),
                ),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
            },
        ),
    ]
