# Generated by Django 3.2.13 on 2022-06-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kikeou", "0004_show_showtype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="show",
            name="accommodation_remarks",
        ),
        migrations.RemoveField(
            model_name="show",
            name="arrival_remarks",
        ),
        migrations.RemoveField(
            model_name="show",
            name="food_remarks",
        ),
        migrations.RemoveField(
            model_name="show",
            name="greeter_remarks",
        ),
        migrations.RemoveField(
            model_name="show",
            name="info_sheet_remarks",
        ),
        migrations.RemoveField(
            model_name="show",
            name="lodge_remarks",
        ),
        migrations.RemoveField(
            model_name="show",
            name="programmer_remarks",
        ),
        migrations.RemoveField(
            model_name="show",
            name="roadmap_remarks",
        ),
        migrations.RemoveField(
            model_name="show",
            name="stage_manager_remarks",
        ),
        migrations.RemoveField(
            model_name="show",
            name="warm_up_spaces_remarks",
        ),
        migrations.AddField(
            model_name="show",
            name="accommodation_comments",
            field=models.TextField(blank=True, verbose_name="accommodation comments"),
        ),
        migrations.AddField(
            model_name="show",
            name="arrival_comments",
            field=models.TextField(blank=True, verbose_name="arrival comments"),
        ),
        migrations.AddField(
            model_name="show",
            name="food_comments",
            field=models.TextField(blank=True, verbose_name="food comments"),
        ),
        migrations.AddField(
            model_name="show",
            name="greeter_comments",
            field=models.TextField(blank=True, verbose_name="greeter comments"),
        ),
        migrations.AddField(
            model_name="show",
            name="info_sheet_comments",
            field=models.TextField(
                blank=True, verbose_name="information sheet comments"
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="lodge_comments",
            field=models.TextField(blank=True, verbose_name="lodge comments"),
        ),
        migrations.AddField(
            model_name="show",
            name="programmer_comments",
            field=models.TextField(blank=True, verbose_name="programmer comments"),
        ),
        migrations.AddField(
            model_name="show",
            name="roadmap_comments",
            field=models.TextField(blank=True, verbose_name="roadmap comments"),
        ),
        migrations.AddField(
            model_name="show",
            name="stage_manager_comments",
            field=models.TextField(blank=True, verbose_name="stage manager comments"),
        ),
        migrations.AddField(
            model_name="show",
            name="warm_up_spaces_comments",
            field=models.TextField(blank=True, verbose_name="warm up spaces comments"),
        ),
    ]
