# Generated by Django 3.2.13 on 2022-06-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kikeou", "0004_auto_20220604_0119"),
    ]

    operations = [
        migrations.CreateModel(
            name="Greeter",
            fields=[],
            options={
                "verbose_name": "greeter person",
                "verbose_name_plural": "greeter persons",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("kikeou.person",),
        ),
        migrations.CreateModel(
            name="LocationContact",
            fields=[],
            options={
                "verbose_name": "location contact",
                "verbose_name_plural": "location contacts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("kikeou.person",),
        ),
        migrations.CreateModel(
            name="Programmer",
            fields=[],
            options={
                "verbose_name": "programmer person",
                "verbose_name_plural": "programmer persons",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("kikeou.person",),
        ),
        migrations.CreateModel(
            name="StageManager",
            fields=[],
            options={
                "verbose_name": "stage manager",
                "verbose_name_plural": "stage managers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("kikeou.person",),
        ),
        migrations.AddField(
            model_name="person",
            name="is_greeter",
            field=models.BooleanField(default=False, verbose_name="is greeter"),
        ),
        migrations.AddField(
            model_name="person",
            name="is_location_contact",
            field=models.BooleanField(
                default=False, verbose_name="is location contact"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="is_programmer",
            field=models.BooleanField(default=False, verbose_name="is programmer"),
        ),
        migrations.AddField(
            model_name="person",
            name="is_stage_manager",
            field=models.BooleanField(default=False, verbose_name="is stage manager"),
        ),
    ]
