# Generated by Django 3.2.13 on 2022-06-04 16:16

import django.db.models.deletion
from django.db import migrations, models

import kikeou.models.utils.abstracts


class Migration(migrations.Migration):

    dependencies = [
        ("kikeou", "0005_auto_20220604_0214"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="street & n°"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="zip code"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=50, verbose_name="city"),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locations",
                        to="kikeou.locationcontact",
                        verbose_name="lodge contact",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        default=kikeou.models.utils.abstracts.get_default_cycle,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="location_related",
                        to="kikeou.cycle",
                        verbose_name="cycle",
                    ),
                ),
            ],
            options={
                "verbose_name": "location",
                "verbose_name_plural": "locations",
            },
        ),
        migrations.CreateModel(
            name="Lodge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gauge",
                    models.PositiveSmallIntegerField(default=0, verbose_name="gauge"),
                ),
                (
                    "ground_floor",
                    models.BooleanField(default=False, verbose_name="ground floor"),
                ),
                (
                    "soundproofed",
                    models.BooleanField(default=False, verbose_name="soundproofed"),
                ),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lodge",
                        to="kikeou.location",
                        verbose_name="location",
                    ),
                ),
            ],
            options={
                "verbose_name": "lodge",
                "verbose_name_plural": "lodges",
            },
        ),
        migrations.CreateModel(
            name="WarmUpPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warmupplace",
                        to="kikeou.location",
                        verbose_name="location",
                    ),
                ),
            ],
            options={
                "verbose_name": "warm-up place",
                "verbose_name_plural": "warm-up places",
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_lodge",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_stage_assignations",
                        to="kikeou.lodge",
                        verbose_name="default lodge",
                    ),
                ),
                (
                    "default_warming_up_place",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_stage_assignations",
                        to="kikeou.warmupplace",
                        verbose_name="default warm up place",
                    ),
                ),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage",
                        to="kikeou.location",
                        verbose_name="location",
                    ),
                ),
            ],
            options={
                "verbose_name": "stage",
                "verbose_name_plural": "stages",
            },
        ),
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodation",
                        to="kikeou.location",
                        verbose_name="location",
                    ),
                ),
            ],
            options={
                "verbose_name": "accommodation",
                "verbose_name_plural": "accommodations",
            },
        ),
    ]
