# Generated by Django 3.2.13 on 2022-06-05 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kikeou", "0005_auto_20220605_1735"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowStaffFunction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "staff function",
                "verbose_name_plural": "staff functions",
            },
        ),
        migrations.CreateModel(
            name="ShowStaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="comments")),
                (
                    "is_present",
                    models.BooleanField(default=True, verbose_name="is present"),
                ),
                (
                    "is_contact_person",
                    models.BooleanField(default=False, verbose_name="contact person"),
                ),
                (
                    "approximate_time_of_arrival",
                    models.BooleanField(
                        default=False, verbose_name="approximate time of arrival"
                    ),
                ),
                (
                    "arrival",
                    models.DateTimeField(blank=True, null=True, verbose_name="arrival"),
                ),
                (
                    "departure",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="departure"
                    ),
                ),
                (
                    "need_accommodations",
                    models.BooleanField(
                        default=None, null=True, verbose_name="need accommodations"
                    ),
                ),
                (
                    "accommodation_comments",
                    models.TextField(blank=True, verbose_name="accommodation comments"),
                ),
                (
                    "accommodation_place",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persons",
                        to="kikeou.accommodation",
                        verbose_name="accommodation place",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showstaffmember_set",
                        to="kikeou.person",
                        verbose_name="person",
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_persons",
                        to="kikeou.show",
                        verbose_name="show",
                    ),
                ),
                (
                    "staff_function",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_members",
                        to="kikeou.showstafffunction",
                        verbose_name="staff function",
                    ),
                ),
            ],
            options={
                "verbose_name": "show staff member",
                "verbose_name_plural": "show staff members",
            },
        ),
    ]
